# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\"5\n\x0e\x43ommandRequest\x12\x12\n\nexecutable\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"1\n\x0f\x43ommandResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t2x\n\x0f\x43ommandExecutor\x12\x33\n\x0e\x45xecuteCommand\x12\x0f.CommandRequest\x1a\x10.CommandResponse\x12\x30\n\x0bKillProcess\x12\x0f.CommandRequest\x1a\x10.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMANDREQUEST']._serialized_start=17
  _globals['_COMMANDREQUEST']._serialized_end=70
  _globals['_COMMANDRESPONSE']._serialized_start=72
  _globals['_COMMANDRESPONSE']._serialized_end=121
  _globals['_COMMANDEXECUTOR']._serialized_start=123
  _globals['_COMMANDEXECUTOR']._serialized_end=243
# @@protoc_insertion_point(module_scope)
